import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './components/navigation/navbar/Navbar';
import Footer from './components/navigation/footer/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Competition',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
